#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

if (class_exists('PHPUnit_Framework_TestCase') && !class_exists('PHPUnit\Framework\TestCase')) {
    fwrite(STDERR, "Editing composer.json");

    $json = \json_decode(\file_get_contents($filename = __DIR__ . '/composer.json'), true);
    $json['autoload-dev']['files'][] = './test-polyfill/TestCase.php';
    \file_put_contents($filename, \json_encode($json));
}
